export const URLS = {
    LOGIN: `/user/login/email`,
    SIGNUP: `/user/signup/email`, 
    VERIFY: `/user/verify-otp`, 
    RESENDOTP: `/user/resend-otp`, 
    UPLOAD: "/upload/file",
    BUSINESS: "/business",
    BUSINESSFILTER: "/business/filter",
    CREATECHAT: "/messaging/chats",
    ADDRESS: "/address",
    SENDCHAT: "/messaging/messages",
    REVIEW: "/review",
    WITHDRAW: `/transactions/withdraw`,
    CANCELLATION: `/transactions/subscription/cancel`,
    CONNECTACCOUNT: (item: string) =>  `/transactions/connect/${item}`,
    ADDACCOUNT: (item: string) =>  `/transactions/connect/onboard/${item}`,
    WALLETBYUSERID: (item: string) =>  `/transactions/wallet/${item}`,
    TRANSACTIONBYUSERID: (item: string) =>  `/transactions/history/${item}`,
    REVIEWBYUSERID: (item: string) => `/review/pending/${item}`,
    REVIEWBYBUSINESSID: (item: string) => `/review/business/${item}`,
    ADDRESSBYID: (item: string) => `/address/${item}`,
    CHATLIST: (item: string) => `/messaging/chats/user/${item}`,
    CHATLISTBYID: (item: string) => `/messaging/chats/${item}`,
    CHATDELETE: (item: string) => `/messaging/chats/${item}`,
    CHATMESSAGES: (item: string) => `/messaging/chats/${item}/messages`,
    BOOKING: "/booking",
    ORDER: "/order",
    SERVICE: "/service",
    TRANSACTION: "/transactions/create",
    VERIFYTRANSACTION: (item: string) => `/transactions/verify-transaction/${item}`, 
    SERVICEBYID: (item: string) => `/service/${item}`,
    SERVICEBUSINESSBYID: (item: string) => `/service/business/${item}`,
    PRODUCT: "/product",
    PRODUCTFILTER: "/product/filter",
    BUSINESSBYID: (item: string) => `/business/${item}`,
    PRODUCTBYID: (item: string) => `/product/${item}`,
    USERUPDATE: (item: string) => `/user/${item}`,
    BOOKMARK: `/bookmarks/toggle`,
    BOOKMARKBYID: (item: string) => `/bookmarks/${item}`
}

// export const IMAGE_URL = process.env.NEXT_PUBLIC_RESOURCE_URL as string; 

// export const RESOURCE_BASE_URL = process.env.NEXT_PUBLIC_AWS_BASE_URL as string; 
